### ISSUE TITLE
Publish to a Maven repository

### ISSUE THREAD

**Issue by Vampire** [eckig/graph-editor#10]
Please also publish to some Maven repository for easier consumption, for example to Maven Central.

**Comment by eckig** [comment]
You are right.

But before we get to that:
I think we need to change the identifier of the package or even rename the base package to adhere to the JPMS standards (base package name = module name = maven identifier).

**Comment by Vampire** [comment]
That is no JPMS standard I'm aware of, not even a convention.
But if you prefer to have it that way, well, change it, it is your project. :-)

**Comment by eckig** [comment]
Starting with Release 11.0.3 and with the help of github actions the artifacts are now generated and published as github packages: https://github.com/eckig/graph-editor/packages

**Comment by Vampire** [comment]
Would you maybe consider reopening and reconsidering this issue?
GitHub Packages are useless unless you consume them from GitHub actions.
GitHub Packages still do not allow anonymous access.

**Comment by eckig** [comment]
I can't make any promise, but I will reopen and investigate when I find the time.

**Comment by elcioabrahao** [comment]
Hi! I would apreciate to much the possibility to reopen this issue and publish to a maven repository! Thanks so much !

**Comment by eckig** [comment]
Okay, I will have to do some preparations but I'm on it.

**Comment by Vampire** [comment]
Should it already be available or is the sync not yet activated?
I cannot see it at https://repo1.maven.org/maven2/io/github/eckig/grapheditor/grapheditor-core/

**Comment by eckig** [comment]
You are right.. my bad.

I just published it from staging.. should take a few hours to appear.

**Comment by Vampire** [comment]
It's available now
