### ISSUE TITLE
After cleaning joints, adjacent joints are not fixed in one dimension

### ISSUE THREAD

**Issue by andi5** [eckig/graph-editor#11]
![2020-01-23 11_41_59-Einstellungen](https://user-images.githubusercontent.com/42928/72977961-d939e580-3dd5-11ea-97aa-c375def99527.png)
Reproduce as follows:
- Open the Graph Editor Demo
- Open the Default Skins - Small sample
- Pick any connection that has one joint
- Add two new joints to it by dragging them from the connection
- Now the first and the third joint cannot be moved in one direction as they are next to a node
- Remove two joints by moving the middle joint onto one of the others
- The remaining joint can be moved in one dimensions now although it should be fixed

**Comment by eckig** [comment]
Thanks for the excellent bug report - I am able to reproduce this with your description. I hope I can fix this any time soon.
