### ISSUE TITLE
Switch connection Detour/Gaps no refresh view container

### ISSUE THREAD

**Issue by syluna** [eckig/graph-editor#193]
To reproduce setup Demo application in 19.0.0 
Menu File -> Load Sample -> Default Skins Large 

When graph is load you can see Detours conexion. 

Go to menu Settings -> Intersection Style -> Gaps 
The view is not refresh... Connections allway in detours in graph view but in data Gaps is correctly setted 

If you do Action Add Node (not is add to the view and Connection is correctly redraw in Gaps

**Comment by eckig** [comment]
Thanks, I'll look into it.

**Comment by syluna** [comment]
I'm searching too because I need to use in this great lib. If I found before you I do PR

**Comment by eckig** [comment]
Should be fixed with the latest commit.

**Comment by syluna** [comment]
Thanks I test and back result.

**Comment by syluna** [comment]
Fixed !
