### ISSUE TITLE
Non-idempotent interconnection

### ISSUE THREAD

**Issue by syluna** [eckig/graph-editor#198]
To reproduce the issue with the demonstration application, launch the application and then select "File -> Load Sample -> Default Skins - Large". You will notice the following crossover on the interconnections:
![image](https://github.com/eckig/graph-editor/assets/1336540/f8be6b93-3dca-40fd-ad24-ba440fccfbbe)
Next, select "Settings -> Interconnection -> Gasp" and immediately after "Settings -> Interconnection -> Detours". You will notice the change in the calculation of the crossovers:
![image](https://github.com/eckig/graph-editor/assets/1336540/47d81328-2995-47bf-bc21-05f95ee356dd)

In version 1.4 that I was using, I did not encounter this difference in behavior. I'm not sure from which version the bug appeared, but I am currently on version 19.0.0. I noticed this issue because I am testing a graph exported as an image, and my image changes between two runs due to this connection drawing inconsistency.

Thanks for your feedback.

**Comment by eckig** [comment]
Curious, I will look into it. But no promises on a timeline.

But thanks for finding and reporting it.

**Comment by eckig** [comment]
Should be fixed with latest commit.

**Comment by syluna** [comment]
I have test this fixed for me it's ok. Thanks.
