### ISSUE TITLE
Disable drag interactions with connections

### ISSUE THREAD

**Issue by danielemaddaluno** [eckig/graph-editor#44]
Is there a way to programmatically block/disable the drag and drop interaction with connections (and joints)?
I would like to leave the drag interaction with boxes, but I want to disable just the connections interactions (which I want to add only programmatically: see  #42 ).

**Comment by eckig** [comment]
Currently that is not possible: With the `GraphEditorProperties` you can control only the editable state of the entire graph.

To break this down into specific elements of the graph (nodes, connectors, connections, etc.) would introduce lots of new properties, but could be done..

**Comment by eckig** [comment]
As this is a nice addition: I added element specific read-only properties.

I'm leaving this issue open to wait for your feedback.

**Comment by danielemaddaluno** [comment]
Simply perfect!
Thank you @eckig!

**Comment by danielemaddaluno** [comment]
Simply perfect!
Thank you @eckig!
