### ISSUE TITLE
How do I automatically position the joints in a connection?

### ISSUE THREAD

**Issue by drinkitup777** [eckig/graph-editor#47]
My graph is a left-to-right flowchart style digraph, and I am trying to get my joints to automatically lay themselves out whenever the nodes are moved. What is the recommended approach?

---

Overriding `GNodeSkin::layoutConnectors()` seems like the way to go, but I've had trouble getting it to work; there seems to be no way to derive the position of a connector relative to the entire graph from either a `GConnection` object or a `GJoint` object. What am I doing wrong?

**Comment by eckig** [comment]
This sounds more like some sort of automatic layout (with collision detection)?

Somewhere I have a prototype of doing just this with the help of the eclipse layout kernel (https://github.com/eclipse/elk).. but it is not ready for prime time.

**Comment by drinkitup777** [comment]
I've played around with `elk` for a while and it seems perfect for my needs. Thanks for the recommendation.
