### ISSUE TITLE
How do I attach arbitrary data to a GNode?

### ISSUE THREAD

**Issue by drinkitup777** [eckig/graph-editor#52]
Lets say that I have some extra data that I want to display in my custom `GNodeSkin`. From what I understand of the [wiki page](https://github.com/eckig/graph-editor/wiki/4.-Connecting-to-Domain-Models), this would be done by creating a new EMF model, and then creating a new `EClass` with the extra attributes needed. Whenever a new node of that extended type is needed, both a `GNode` and a `MyExtendedGNode` are instantiated, with the same ID, and both are added to the `GModel`.

But then how does the custom `GNodeSkin` get access to the `MyExtendedGNode` instance? Do I use the `GNode` to look up the `MyExtendedGNode` instance? Where do I do this? Do I do this in the skin factory? Is there a function I can call such as `getMyExtendedGNodeById(String id)`, or do I manually keep a  `Map<String, MyExtendedGNode>` that acts as an index for the extra attributes? I'm confused. What is the recommended approach? (Or am I going about this entirely the wrong way?)

**Comment by eckig** [comment]
The `GNode` is added to the `GModel` but your `MyExtendedGNode` needs to be added to the `MyExtendedGModel` (4.2 in the wiki).

In the `GNodeSkin` you can access the `GModel` with `getGraphEditor().getModel()` and from that you can retrieve your custom Model (via the editing domain).

If you frequently do this kind of a query, you should cache the value somehow, but that is up to you.
