### ISSUE TITLE
Dragging a selection box goes out-of-bounds when graph container is larger than graph

### ISSUE THREAD

**Issue by drinkitup777** [eckig/graph-editor#53]
Platform: Windows 10 x64 build 19041
graph-editor version: commit 70a8567 from repo latest as of 2020/12/14
Tested Java versions: Adopt OpenJDK 15 and Amazon Coretto 11

Demo: https://streamable.com/d4hqeq
Demo code: https://pastebin.com/5kpBNn7d

Steps to reproduce:
  1. Instantiate a `GModel`, a `GraphEditor`, and a `GraphEditorContainer`. (Optional: enable minimap view)
  2. Resize the `GraphEditorContainer` so that it's larger than the `GraphEditor`
  3. Click and drag a selection box past the top-left boundaries of the graph
  4. Observe that the graph suddenly flickers to the right of the screen
  5. Observe that the minimap, if enabled, displays an impossible viewing rectangle--one that's out of the bounds of the graph itself

This bug also occurs if you zoom out too far using the minimap.

**Comment by eckig** [comment]
Can confirm. I will look into this.

**Comment by eckig** [comment]
I added a commit that should fix the selection box and minimap locator - can you verify that it is working for you?

**Comment by drinkitup777** [comment]
Yes, I can verify both fixes are working. All that's left now is the graph jumping to the right of the screen.

**Comment by eckig** [comment]
Yes, you are right. Should be resolved by now.

**Comment by drinkitup777** [comment]
Yup, tested and issue is fixed.
