### ISSUE TITLE
How can I implement drag-and-drop between two GNodeSkins?

### ISSUE THREAD

**Issue by drinkitup777** [eckig/graph-editor#54]
I want to implement drag-and-drop between nodes in the graph editor: when one node is dropped on top of another, a connection is formed. How should I approach this?

---

What I've tried is this:

```java
public class MyNodeSkin extends GNodeSkin {
    public MyNodeSkin(GNode node) {
        super(node);
        // ...
        this.getRoot().addEventHandler(MouseEvent.DRAG_DETECTED, this::onDragDetected);
    }

    private void onDragDetected(MouseEvent ev) {
        System.out.println("drag detected");

        Dragboard db = this.getRoot().startDragAndDrop(TransferMode.ANY);
        ClipboardContent content = new ClipboardContent();
        content.putString("Lorem ipsum dolor sit amet");
        db.setContent(content);
    }
   
    // ...
}
```

.. but calling `db.setContent(content)` stops the node from being dragged. What can I do to implement this?

**Comment by eckig** [comment]
I would advise against doing that: The whole graph editor is build around the idea of `GConnection`s between `GConnector`s.

If you really want to do this, you should take a look at `ConnectorDragManager` where the Drag and Drop handlind is implemented for the `GConnector`s. You would need to adapt that code for `GNode`s,
