### ISSUE TITLE
Can one see such great customized implementation in demo?

### ISSUE THREAD

**Issue by ValeriusGC** [eckig/graph-editor#6]
Hello, i am impressed with _Example of a fully customized implementation_.
But in Demo i see only _Squares_. 
Is there any way to see it in action?

**Comment by eckig** [comment]
As you may have guessed: The implementation is closed source and thus it is difficult to provide more footage of the example.

But is there anything in particular you are interested in?

**Comment by ValeriusGC** [comment]
Nope, this is not obvious from the fact itself.
And yes. I'd like to make something more useful than just "_net of ordinary squares_", and specifically set of binary logic objects such as "AND", "OR", "XOR", etc. and linking them in binary scheme. Alas, I am noob in that, and it was very useful for me to see example how to organize variations in skins, nodes, connectors and connections. This could save me a lot of time and avoid some traps.
Moreover i have an idea to add feature like **Pages**, **Export to PDF** and **Print** to this project with and instead I could spend my free time on it. Here my plan )))

**Comment by ValeriusGC** [comment]
From time to time one need to voice your problem to fine solution. This is it. 
As I see I just should create my own xxxSkinConstants, xxxSkinController, and bunch of my xxxnNodeSkins with particular behaviour, should I? And all of them will be (de)serialized 'out-from-the-box'?

**Comment by eckig** [comment]
Yes, I know the documentation needs an update (as there is not really a documentation) - It is on the to do list.

As for creating custom editors, the basic steps would be:

1. Do the attributes in the Model Project work for you / suffice?
      - If not: You will need to create a new and separate model with Eclipse EMF, generate it and add it to your project.
      - You can think of this new model as kind of a mirror: Do you need extra attributes for a `GNode`? Then create a `MyExtraNode` in your custom model, etc.
      - This new model needs to be added to the same resource set as the `GModel` of the graph editor: `EditingDomain.getResourceSet().getResources().add()`
      - When adding/removing elements from the graph editor make sure that your elements are added/removed, too.
2. Create and register custom skins.

**Comment by eckig** [comment]
I have written some more Wiki pages to document these steps.. Hopefully this is enough provide some hints on how to start: https://github.com/eckig/graph-editor/wiki
