### ISSUE TITLE
I don't quite understand why this project used EMF to build a data model. Can the role of EMF in this project be replaced by json(e.g. Jackson)?

### ISSUE THREAD

**Issue by weixiaoRetour** [eckig/graph-editor#74]

**Comment by eckig** [comment]
If we talking about the data model alone: Then yes, one could replace it with JSON.

But, there are other advantages of using an EMF model, from the top of my head the most important ones (there are possibly many more):

- Full undo/redo support through commands
- Ability to plug into the EMF Ecosystem, e.g. use ELK for automatic layouting of a graph

**Comment by eckig** [comment]
New attributes for custom business logic should be added through a separate domain model: https://github.com/eckig/graph-editor/wiki/4.-Connecting-to-Domain-Models

**Comment by weixiaoRetour** [comment]
> If we talking about the data model alone: Then yes, one could replace it with JSON.
> 
> But, there are other advantages of using an EMF model, from the top of my head the most important ones (there are possibly many more):
> 
> * Full undo/redo support through commands
> * Ability to plug into the EMF Ecosystem, e.g. use ELK for automatic layouting of a graph

EMF also seems to have its own minimap.
