### ISSUE TITLE
Please join forces

### ISSUE THREAD

**Issue by Vampire** [eckig/graph-editor#8]
There is another active fork at https://github.com/imzhukov/graph-editor, probably because you disconnected your fork from the upstream repository and it was not found by those guys.

Maybe it would make sense to join forces and combine the improvements done in both forks for the benefit of all of us? :-)

**Comment by eckig** [comment]
Interesting.
When I decided to detach the fork, the original repository was inactive and there was no other active fork.

As of now both forks have put quite some work into this framework and I do not see an easy way of merging both. Especially as they do not have an issue tracker to contact them..

Besides that: They heavily modified the EMF model for the graph itself.
It is always tempting to modify the EMF model, so it is easier to adapt to custom business logic. But the original approach of Robert (which I tried to follow) was to create a separate model for the business logic.

**Comment by Vampire** [comment]
You can try to contact them via the E-Mail as which they commit. :-)
I also dropped them a mail with the same request due to the missing issue tracker, pointing here.
If it does not work out, then not, I just thought both of you and we all would benefit if efforts are combined if possible. :-)
