### ISSUE TITLE
How to package the project?

### ISSUE THREAD

**Issue by weixiaoRetour** [eckig/graph-editor#86]
I used the 'mvn package' command to package the project, and then run the generated 'graph-editor-demo-17.0.0-jar-with-dependencies.jar' file, the program can be started normally, but the node cannot be added , check the exception information, and find that the error occurs in the "org.eclipse.emf.*" package. I suspect that my packaging method is incorrect. I would like to ask how to correctly package the project into an executable program?

**Comment by eckig** [comment]
Packaging this project itself is done by this project (and the github pipelines).

Normally you would create your own project (with a dependency linking to this library) to create something with the help of this library and then package it.

There are several ways how to package a java application but that is not the purpose of this library, see for example this discussion here: https://stackoverflow.com/questions/7915315/how-can-i-package-a-java-desktop-application

**Comment by eckig** [comment]
No, nothing special for that package.
