### ISSUE TITLE
Produce JavaDoc JAR

### ISSUE THREAD

**Issue by Vampire** [eckig/graph-editor#9]
Please also build and provide a JavaDoc JAR

**Comment by eckig** [comment]
This should be an easy modification to the `pom.xml`?
Would be very nice of you to create a pull request for this.

**Comment by Vampire** [comment]
Well, if I would open a pull request for this, it would remove all POMs and replace them with a Gradle build. :-D
I prevent using Maven where I can as Gradle is much better and the only valid reasons to use Maven imho are, if you either are too used to Maven to switch or need to use some Maven plugin that has no alternative.

Besides that, it is probably not a simple POM change, as the JavaDoc does not even build due to errors in the markup.

**Comment by eckig** [comment]
Javadoc JAR is now generated during maven builds: https://github.com/eckig/graph-editor/packages

Still getting some errors from this bug: https://issues.apache.org/jira/browse/MJAVADOC-623
But the JAR is generated anway..
